"""
Example output showing what the agent produces
"""

# Example 1: Console Output (Dry Run)
"""
============================================================
K8s Image Updater Agent Starting
Date: 2026-02-05T09:00:00.000000
============================================================
Loading configuration from config.yaml
✓ Using GITHUB_TOKEN from environment
✓ Configuration validated successfully

Scanning Kubernetes cluster for deployments...
✓ Using in-cluster Kubernetes configuration
Scanning namespace: default
Scanning namespace: sonarr
Scanning namespace: radarr
Scanning namespace: overseerr
Scanning namespace: homepage
... (15 more namespaces)

Found 23 deployments

Checking registries for image updates...
Checking sonarr/sonarr - lscr.io/linuxserver/sonarr:4.0.16.2944-ls301
  ✓ Update available: sonarr/sonarr 4.0.16.2944-ls301 → 4.0.17.3001-ls302

Checking radarr/radarr - lscr.io/linuxserver/radarr:5.9.1.9070-ls251
  ✓ Update available: radarr/radarr 5.9.1.9070-ls251 → 5.10.0.9100-ls253

Checking overseerr/overseerr - linuxserver/overseerr:1.34.0
  ✓ Update available: overseerr/overseerr 1.34.0 → 1.35.0

Checking homepage/homepage - ghcr.io/gethomepage/homepage:v0.9.5
  No update available

... (19 more deployments checked)

Found 3 updates available

============================================================
WEEKLY IMAGE UPDATE SUMMARY
============================================================
Date: 2026-02-05
Total Updates: 3

Updates by Category:

  Major: 0
  Minor: 1
  Patch: 2

Detailed Updates:

  • sonarr/sonarr: lscr.io/linuxserver/sonarr:4.0.16.2944-ls301 → :4.0.17.3001-ls302 [PATCH]
  • radarr/radarr: lscr.io/linuxserver/radarr:5.9.1.9070-ls251 → :5.10.0.9100-ls253 [MINOR]
  • overseerr/overseerr: linuxserver/overseerr:1.34.0 → :1.35.0 [MINOR]

============================================================

Dry-run mode: Skipping PR creation

============================================================
K8s Image Updater Agent Completed Successfully
============================================================
"""

# Example 2: GitHub Pull Request Output
"""
Title: 🤖 Weekly Container Image Updates - 2026-02-05 (3 updates)

Body:
---

## 🤖 Automated Container Image Updates

This PR contains automated updates to container images in Kubernetes manifests.

### Summary

```
============================================================
WEEKLY IMAGE UPDATE SUMMARY
============================================================
Date: 2026-02-05
Total Updates: 3

Updates by Category:

  Major: 0
  Minor: 1
  Patch: 2

Detailed Updates:

  • sonarr/sonarr: lscr.io/linuxserver/sonarr:4.0.16.2944-ls301 → :4.0.17.3001-ls302 [PATCH]
  • radarr/radarr: lscr.io/linuxserver/radarr:5.9.1.9070-ls251 → :5.10.0.9100-ls253 [MINOR]
  • overseerr/overseerr: linuxserver/overseerr:1.34.0 → :1.35.0 [MINOR]

============================================================
```

### Detailed Changes

#### Namespace: `sonarr`

- 🟢 **sonarr** `lscr.io/linuxserver/sonarr:4.0.16.2944-ls301` → `:4.0.17.3001-ls302` *(patch)*

#### Namespace: `radarr`

- 🟡 **radarr** `lscr.io/linuxserver/radarr:5.9.1.9070-ls251` → `:5.10.0.9100-ls253` *(minor)*

#### Namespace: `overseerr`

- 🟡 **overseerr** `linuxserver/overseerr:1.34.0` → `:1.35.0` *(minor)*

### 🔍 Review Checklist

- [ ] Review the version changes above
- [ ] Check for any breaking changes in changelogs
- [ ] Verify tests pass
- [ ] Deploy to staging first if available

---

🤖 *Generated by K8s Image Updater Agent on 2026-02-05 09:00:00 UTC*

---

Files Changed:
- kubernetes/sonarr/deployment.yaml
- kubernetes/radarr/deployment.yaml
- Manifest/overseerr/overseerr-deployment.yaml

Commits:
- Update images in kubernetes/sonarr/deployment.yaml
- Update images in kubernetes/radarr/deployment.yaml
- Update images in Manifest/overseerr/overseerr-deployment.yaml

Labels: automated, dependencies, kubernetes
"""

# Example 3: File Diff (kubernetes/sonarr/deployment.yaml)
"""
@@ -28,7 +28,7 @@ spec:
       securityContext:
         runAsUser: 1000
       containers:
       - name: sonarr
-        image: lscr.io/linuxserver/sonarr:4.0.16.2944-ls301
+        image: lscr.io/linuxserver/sonarr:4.0.17.3001-ls302
         imagePullPolicy: IfNotPresent
         env:
         - name: PUID
"""

# Example 4: Slack Notification (if implemented)
"""
📦 K8s Image Updates Available!

A new PR has been created with 3 container image updates:
- 1 minor update
- 2 patch updates

Review it here: https://github.com/mtstrong/homelab/pull/123

Summary:
• sonarr: 4.0.16 → 4.0.17 (patch)
• radarr: 5.9.1 → 5.10.0 (minor)
• overseerr: 1.34.0 → 1.35.0 (minor)
"""

# Example 5: Job Logs in Kubernetes
"""
$ kubectl logs -n image-updater job/k8s-image-updater-1738746000

Installing dependencies...
Collecting kubernetes==31.0.0
  Downloading kubernetes-31.0.0-py2.py3-none-any.whl (1.8 MB)
Collecting PyGithub==2.5.0
  Downloading PyGithub-2.5.0-py3-none-any.whl (357 kB)
...
Successfully installed kubernetes-31.0.0 PyGithub-2.5.0 PyYAML-6.0.2 ...

Cloning repository...
Cloning into '/workspace'...
remote: Enumerating objects: 1523, done.
remote: Counting objects: 100% (423/423), done.
remote: Compressing objects: 100% (187/187), done.
remote: Total 1523 (delta 256), reused 376 (delta 225)
Receiving objects: 100% (1523/1523), 2.15 MiB | 12.34 MiB/s, done.
Resolving deltas: 100% (678/678), done.

Running image updater...
2026-02-05 09:00:15 - INFO - K8s Image Updater Agent Starting
2026-02-05 09:00:15 - INFO - Loading configuration from /config/config.yaml
2026-02-05 09:00:15 - INFO - Using GITHUB_TOKEN from environment
2026-02-05 09:00:15 - INFO - Configuration validated successfully
2026-02-05 09:00:15 - INFO - Scanning Kubernetes cluster for deployments...
2026-02-05 09:00:16 - INFO - Using in-cluster Kubernetes configuration
2026-02-05 09:00:17 - INFO - Found 23 deployments
2026-02-05 09:00:17 - INFO - Checking registries for image updates...
2026-02-05 09:00:20 - INFO -   ✓ Update available: sonarr/sonarr 4.0.16 → 4.0.17
2026-02-05 09:00:22 - INFO -   ✓ Update available: radarr/radarr 5.9.1 → 5.10.0
2026-02-05 09:00:24 - INFO -   ✓ Update available: overseerr/overseerr 1.34.0 → 1.35.0
2026-02-05 09:00:30 - INFO - Found 3 updates available
2026-02-05 09:00:30 - INFO - Updating manifest files...
2026-02-05 09:00:30 - INFO - Found 28 deployment manifest files
2026-02-05 09:00:31 - INFO - Updating /workspace/kubernetes/sonarr/deployment.yaml
2026-02-05 09:00:31 - INFO -   Updated sonarr: 4.0.16 → 4.0.17
2026-02-05 09:00:31 - INFO - Updating /workspace/kubernetes/radarr/deployment.yaml
2026-02-05 09:00:31 - INFO -   Updated radarr: 5.9.1 → 5.10.0
2026-02-05 09:00:31 - INFO - Updating /workspace/../Manifest/overseerr/overseerr-deployment.yaml
2026-02-05 09:00:31 - INFO -   Updated overseerr: 1.34.0 → 1.35.0
2026-02-05 09:00:31 - INFO - Successfully updated 3 manifest files
2026-02-05 09:00:31 - INFO - Creating GitHub Pull Request...
2026-02-05 09:00:31 - INFO - Creating branch: image-updates/20260205-090031
2026-02-05 09:00:32 - INFO - ✓ Branch created: image-updates/20260205-090031
2026-02-05 09:00:33 - INFO -   ✓ Updated: kubernetes/sonarr/deployment.yaml
2026-02-05 09:00:34 - INFO -   ✓ Updated: kubernetes/radarr/deployment.yaml
2026-02-05 09:00:35 - INFO -   ✓ Updated: Manifest/overseerr/overseerr-deployment.yaml
2026-02-05 09:00:36 - INFO - ✓ Pull request created: https://github.com/mtstrong/homelab/pull/123
2026-02-05 09:00:36 - INFO - Added labels: automated, dependencies, kubernetes
2026-02-05 09:00:36 - INFO - ============================================================
2026-02-05 09:00:36 - INFO - K8s Image Updater Agent Completed Successfully
2026-02-05 09:00:36 - INFO - ============================================================

Job completed successfully
"""

# Example 6: No Updates Available
"""
============================================================
K8s Image Updater Agent Starting
Date: 2026-02-05T09:00:00.000000
============================================================
Loading configuration from config.yaml
Scanning Kubernetes cluster for deployments...
Found 23 deployments
Checking registries for image updates...
... (checking all images)
Found 0 updates available
No updates available. Exiting.
============================================================
K8s Image Updater Agent Completed Successfully
============================================================
"""

# Example 7: Error Handling
"""
============================================================
K8s Image Updater Agent Starting
Date: 2026-02-05T09:00:00.000000
============================================================
Loading configuration from config.yaml
ERROR - GitHub token not configured. Set in config.yaml or GITHUB_TOKEN env var
Fatal error: GitHub token not configured

-- OR --

Scanning Kubernetes cluster for deployments...
ERROR - Could not configure Kubernetes client: Unable to load config
Fatal error: Could not configure Kubernetes client

-- OR --

Creating GitHub Pull Request...
ERROR - GitHub API error: 401 Unauthorized
ERROR - Token may be invalid or expired
Fatal error: GitHub API error
"""
